version: "2"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"

  # dot-print-backend:
  #   image: dot-print-backend:latest
  #   ports:
  #     - "3000:3000"